
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 09 16:03:07 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVEQ = 42;
  public static final int CONST = 3;
  public static final int EEQUAL = 28;
  public static final int MODEQ = 43;
  public static final int GRT = 30;
  public static final int NUMCONST = 46;
  public static final int NOTEQUAL = 29;
  public static final int LPAREN = 22;
  public static final int SEMI = 4;
  public static final int CONTINUE = 9;
  public static final int MINUS = 35;
  public static final int LESS = 32;
  public static final int FOR = 24;
  public static final int STATIC = 7;
  public static final int RPAREN = 23;
  public static final int AND = 17;
  public static final int OR = 16;
  public static final int ELESS = 33;
  public static final int COMMA = 5;
  public static final int CLASS = 12;
  public static final int INC = 25;
  public static final int DIV = 39;
  public static final int PLUSEQ = 36;
  public static final int MINUSEQ = 37;
  public static final int PLUS = 34;
  public static final int IF = 44;
  public static final int DOT = 8;
  public static final int EGRT = 31;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 27;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 38;
  public static final int MOD = 40;
  public static final int IDENT = 47;
  public static final int BREAK = 10;
  public static final int VOID = 48;
  public static final int MULEQ = 41;
  public static final int ELSE = 45;
  public static final int LBRACE = 18;
  public static final int LSQUARE = 20;
  public static final int READ = 13;
  public static final int CHARCONST = 49;
  public static final int RSQUARE = 21;
  public static final int RBRACE = 19;
  public static final int BOOLCONST = 50;
  public static final int EXTENDS = 6;
  public static final int DEC = 26;
  public static final int PRINT = 14;
}

