
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 27 11:02:31 CEST 2016
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 16;
  public static final int EEQUAL = 33;
  public static final int LBRA = 21;
  public static final int BCONST = 14;
  public static final int LPAREN = 19;
  public static final int SEMI = 3;
  public static final int LESS = 37;
  public static final int MINUS = 24;
  public static final int RPAREN = 20;
  public static final int AND = 31;
  public static final int PER = 29;
  public static final int OR = 30;
  public static final int COMMA = 4;
  public static final int CLASS = 7;
  public static final int INC = 25;
  public static final int DIV = 28;
  public static final int PLUS = 23;
  public static final int IF = 39;
  public static final int DOTT = 9;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int EQUAL = 32;
  public static final int NEW = 44;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int BEQUAL = 36;
  public static final int RBRA = 22;
  public static final int NUMBER = 11;
  public static final int BREAK = 42;
  public static final int BIGGER = 35;
  public static final int IDENT = 12;
  public static final int VOID = 8;
  public static final int CCONST = 13;
  public static final int ELSE = 40;
  public static final int LBRACE = 17;
  public static final int READ = 43;
  public static final int LEQUAL = 38;
  public static final int WHILE = 41;
  public static final int RBRACE = 18;
  public static final int EXTENDS = 10;
  public static final int PROG = 2;
  public static final int DIFF = 34;
  public static final int DEC = 26;
  public static final int SCONST = 15;
  public static final int PRINT = 5;
}

